apiVersion: v1
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data/db/vol1
---
  apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    name: "mongodb-pvc"
    namespace: "default"
    labels:
      app: "mongo-db"
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: local-storage
---
  apiVersion: "apps/v1"
  kind: "StatefulSet"
  metadata:
    name: "mongo-db"
    namespace: "default"
  spec:
    selector:
      matchLabels:
        app: "mongo-db"
    replicas: 1
    template:
      metadata:
        labels:
          app: "mongo-db"
      spec:
        containers:
          -
            name: "mongo-db"
            image: "mongo:4.4.18"
            imagePullPolicy: "IfNotPresent"
            ports:
              -
                containerPort: 27017
                name: "mongodb"
            volumeMounts:
              -
                name: "mongodb-persistent-storage"
                mountPath: "/data/db"
        volumes:
          -
            name: "mongodb-persistent-storage"
            persistentVolumeClaim:
              claimName: "mongodb-pvc"
---
  apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "mongo-db"
    namespace: "default"
    labels:
      app: "mongo-db"
  spec:
    ports:
      -
        name: "mongodb"
        port: 27017
        nodePort: 30332
    type: "NodePort"
    selector:
      app: "mongo-db"



